---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# do NOT set "namespace" here since this will place the certifiactes for the
# webhooks in the wrong namespaces!
commonLabels:
  app.kubernetes.io/name: cert-manager
resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.11.1/cert-manager.yaml
  - clusterissuers.yaml
