---
- name: restart ssh.service
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: restart ssh.socket
  ansible.builtin.systemd_service:
    name: ssh.socket
    state: restarted
    daemon_reload: true
