---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
commonLabels:
  app.kubernetes.io/name: ingress-nginx
resources:
  - github.com/kubernetes/ingress-nginx/deploy/static/provider/baremetal?ref=controller-v1.5.1
