---
- hosts: all
  become: true
  roles:
    - role: common
      tags: common
    - role: firewall
      tags: firewall
    - role: backup
      tags: backup

- hosts: pocket_id
  become: true
  roles:
    - role: pocket_id
      tags: pocket_id
