---
- name: Install k0s binary
  ansible.builtin.shell:
    cmd: |
      curl -sSLf https://get.k0s.sh | sudo sh
    creates: /usr/local/bin/k0s

- name: Ensure k0s config dir exists
  ansible.builtin.file:
    path: /etc/k0s
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create k0s config file
  ansible.builtin.template:
    src: k0s.yaml.j2
    dest: /etc/k0s/k0s.yaml
  vars:
    api_address: "{{ ansible_host }}"
    api_sans: |
      {{
        ['localhost', 'ares', ansible_hostname]
        ansible_all_ipv4_addresses +
        ansible_all_ipv6_addresses +
      }}
